version: '3.9'

services:
  apache:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: 'apache'
    ports:
      - '8020:80'
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./docker/server/php/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini

  maria-db:
    image: mariadb:10.5.9
    container_name: 'maria-db'
    restart: always
    ports:
      - '8040:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'homestead'
    volumes:
      - db_data:/var/lib/mysql
      # - './docker/db/db_data:/var/lib/mysql'
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data: